[config]
default_to_workspace = false

[env]
PROFILE_NAME = "dev"
BUILD_TYPE = "debug"

[env.production]
PROFILE_NAME = "release"
BUILD_TYPE = "release"

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.xwin]
condition = { files_not_exist = [".xwin"], platforms = ["linux"] }
install_crate = { crate_name = "xwin", binary = "xwin", test_arg = "--help" }
command = "xwin"
args = ["--accept-license", "splat", "--output", ".xwin"]

[tasks.build]
command = "cargo"
args = ["build", "--profile=${PROFILE_NAME}"]
dependencies = ["xwin"]

[tasks.test]
command = "cargo"
args = ["test", "--", "--nocapture"]

[tasks.copy]
env_files = [{ path = "./.env" }]
command = "cp"
args = [
    "-v",
    "./target/x86_64-pc-windows-msvc/${BUILD_TYPE}/bg3_debug_tool.dll",
    "./target/x86_64-pc-windows-msvc/${BUILD_TYPE}/bg3-debug-tool.exe",
    "${GAME_PATH}/bin/",
]
dependencies = ["build"]

[tasks.run]
command = "steam"
args = ["-applaunch", "1086940"]
dependencies = ["copy"]

[tasks.attach]
command = "socat"
args = ["tcp4:127.0.0.1:9003,reuseaddr,forever", "-"]
dependencies = ["run"]
