[build]
target = "x86_64-pc-windows-msvc"

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-Lnative=.xwin/crt/lib/x86_64",
    "-Lnative=.xwin/sdk/lib/ucrt/x86_64",
    "-Lnative=.xwin/sdk/lib/um/x86_64",
    "-Lthird-party",
    "-Lthird-party/SDL2-2.30.0/lib/x64",
]
