[package]
name = "game-object"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[profile.dev]
panic = "abort"

[profile.release]
lto = "fat"
panic = "abort"

[dependencies]
anyhow = "1.0"
syn = { version = "2.0", features = ["extra-traits", "full"] }
quote = "1.0"
proc-macro2 = "1.0"
